### PR TITLE
Feat/create an omnisearch

### PR DESCRIPTION
**Pull request by helakaraa**

### CODE REVIEW

**Comment by helakaraa** [comment]
### **Backend:** SearchController

- [x]  Add control on search by checking the user profile.
- [x]  Implement a generic view query by tenant.
- [x]  Ensure that for a user on the home page, data is filtered to show only information related to their tenants.
- [x]  Add a description field with rank B and prioritize the name field with rank A.
- [x]  Check user rights on projects.
- [ ]  Add search view entity for webHooks, Users, Tenants.

### **Frontend:** : SearchComponent 
- [x]  Implement table filtering.
- [x]  Add two buttons to switch between all tenants and the current tenant.
- [x]  Change the design of the modal button.
- [x]  Highlight selected names in the table of features and keys.
- [x]  Ensure mobile screen displays correctly.
- [x]  Clear the search field when changing tenants.
- [x]  Make shown results clickable and navigate to the corresponding page.
- [x]  On the home page, allow admins to search for all information, limited to their related tenants.
- [x]  Design the text search input.
- [x]  Ensure the search field considers tenant changes.
- [ ]   Show search results of webHooks, Users, Tenants.
### **Testing**:

- [x]  Add backend tests (**SearchAPISpec**).
- [ ]  Add frontend tests.

**Comment by helakaraa** [comment]
Reviewed By  @ptitFicus 

- [ ] Search query : modify the backend search query in order to be able to search with a starting words.
- [ ] Add focus on search typing input field.
- [ ] Check if a user has an Admin right or  Izanami Admin right => so we have no need to filter on projects ..
- [ ] Check if we can create an index on a view in postgresql.  
- [ ] Change query variable to query list in search query. 
- [ ] Don’t show search button, if a user has no tenant.
- [ ] Add tenant cloud icon in the button of the search modal.
- [ ] Remove the command K shortcut of the search button.
- [ ] Replace "Esc"  by "Close".
- [ ] Add a clear icon in search input in order to remove easily the typed words.
- [ ] Modify SearchModalContent.tsx (change the location of some functions , use debounce query directly in onChange input function).
- [ ] Add search view for contexts.

**Comment by helakaraa** [comment]
### Added modifications 

- [ ] Change fts to fuzzystrmach query. 
- [ ] Add index on name and description fields for searchable entities. 
- [ ] Add search view for projects contexts and global contexts. 
- [ ] Add filter on projects contexts and global contexts.
- [ ] Add Extensions (fuzzystrmatch and pg_trgm) to postgresSQL.
- [ ] Limit the number of shown search results.

**Comment by ptitFicus** [comment]
image

When "All tenants" is selected, placeholder message should be "Search in all tenants"

**Comment by ptitFicus** [comment]
When I am on a project page, searching for a feature that's on the page does not filter the feature table when I select seaech result.

**Comment by ptitFicus** [comment]
image

Global subcontext icon is wrong, it should be the planet with the filter, as for "prod" context

**Comment by ptitFicus** [comment]
image

This should probably be "Click to search", since we can't actually type in this field

**Comment by ptitFicus** [comment]
When searching tenant project of features with a tenant admin user (that has no specific rights on these projects), search returns nothing.

**Comment by ptitFicus** [comment]
Search does not find project on which user has read/write/admin rights (without being a tenant or izanami admin)

**Comment by helakaraa** [comment]
- [ ] Show history of search. 
- [ ] Regroup global contexts with projects contexts in one section as contexts.
- [ ] Correction of the project link having a description. 
- [ ] Correction of contexts links (if we have a context dev and  dev-test and we click on dev-test we see that even dev is opened).
- [ ] Change the search link of a context to search query param {contexts/?query= …… query params}).
- [ ] Icon search global context to be modified.
- [ ] Remove tenant name in display search if we are already on a selected tenant .
- [ ] Icon search to minimize size.
- [ ] If we can add the option to search only on a specific category ( example search only in projects).
- [ ] We need to see if we can make the rank of the query as global param , we added it as default to  0.2.
- [ ] In display search results, we should highlight the searched word (uppercase , underlining …). 
- [ ] Add wasm scripts for search field.

**Comment by ptitFicus** [comment]
Closed since 2f09781de34fa975e8b8347307f138bfdf9f665e has been merged, remaining taks are in https://github.com/MAIF/izanami/issues/857

**Pull request closed without merging**
